### ISSUE TITLE
Unable to install version 2.3

### ISSUE THREAD

**Issue by sothea-beniten** [iambrandontaylor/django-admin-sortable#258]
I'm trying to upgrade admin-sortable from version 2.2 to 2.3 but I got an issued **UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2883: character maps to <undefined>** . 

Here is the full log when I install latest version
```
Requirement already satisfied: django-admin-sortable in d:\my_code\techis\source\test upgrade\backend\env\lib\site-packages (2.2.4)
Collecting django-admin-sortable
  Using cached django-admin-sortable-2.3.tar.gz (106 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Root\AppData\Local\Temp\pip-install-o20ggg3o\django-admin-sortable_dd3208e845fb48a19ad72839869c873a\setup.py", line 4, in <module>
          README = readme_file.read()
        File "C:\Users\Root\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2883: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by LEAGUEDORA** [comment]
You can use my forked & fixed repo.
To install use ```git clone git+https://github.com/LEAGUEDORA/django-admin-sortable.git```
